# All targets

all:	pingpong chain hash # oneway self

# programs

pingpong:     pingpong.o
	$(LINK) $(LINKFLAGS) pingpong.o $(SYSLIB) -o pingpong

chain:   chain.o
	$(LINK) $(LINKFLAGS) chain.o $(SYSLIB) -o chain

hash: hash.o hashlittle.o
	$(LINK) $(LINKFLAGS) hash.o hashlittle.o $(SYSLIB) -o hash

#oneway: oneway.o
#	$(LINK) $(LINKFLAGS) oneway.o $(SYSLIB) -o oneway

#self: self.o
#	$(LINK) $(LINKFLAGS) self.o $(SYSLIB) -o self

