# Makefile for PHISH apps

CC =		g++
CCFLAGS =	-g -O -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O 
SYSLIB =	-lmpich -lmpl -lpthread

# PHISH SPs and stand-alone programs

include Makefile.common

# Clean

clean:
	@rm -f *.o

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
