# Makefile for MPI-only benchmarks

CC =		g++
CCFLAGS =	-g -O -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O 
SYSLIB =	-lmpich -lmpl -lpthread

# Targets

all:	pingpong chain hash # oneway self

pingpong:     pingpong.o
	$(LINK) $(LINKFLAGS) pingpong.o $(SYSLIB) -o pingpong

chain:   chain.o
	$(LINK) $(LINKFLAGS) chain.o $(SYSLIB) -o chain

hash: hash.o hashlittle.o
	$(LINK) $(LINKFLAGS) hash.o hashlittle.o $(SYSLIB) -o hash

# Clean

clean:
	@rm -f *.o
	@rm -f pingpong chain hash

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
