# linux = RedHat Linux box, g++4, MPICH2

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler/linker settings
# specify flags and libraries needed for your compiler

CC =		g++
CCFLAGS =	-g -O -DMPICH_IGNORE_CXX_SEEK -I../src
LINK =		g++
LINKFLAGS =	-g -O 
LIB =		../src/libphish.a
SYSLIB =	-lmpich -lmpl -lpthread

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

$(EXE):		$(EXE).o
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) $(EXE).o $(LIB) $(SYSLIB) -o $(EXE)

# Rules

%.o:%.cpp
	$(CC) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
