# Makefile for PHISH library: Mac with mpic++, MPICH, ZMQ

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler settings

CC =		mpic++
CCFLAGS =	-g -O
ARCHIVE =	ar
ARFLAGS =	-rc

# MPI settings
# only needed to build MPI version of PHISH library
# INC = path for mpi.h, other compiler settings

MPI_INC =	-DMPICH_IGNORE_CXX_SEEK

# ZMQ settings
# only needed to build ZMQ or MPI+ZMQ version of PHISH library
# INC = path for zmq.h, other compiler settings

ZMQ_INC =	-I~/zmq

# ---------------------------------------------------------------------
# targets = 3 versions of PHISH library: MPI, MPI+ZMQ, ZMQ
# no need to edit this section

LIBM =	libphish-mpi.a
LIBMZ =	libphish-mpizmq.a
LIBZ =	libphish-zmq.a

mpi:	
	$(CC) $(CCFLAGS) $(MPI_INC) -c phish-mpi.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIBM) phish-mpi.o hash.o

mpizmq:	
	$(CC) $(CCFLAGS) $(MPI_INC) $(ZMQ_INC) -DPHISH_MPI_ZMQ -c phish-mpi.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIBMZ) phish-mpi.o hash.o

zmq:
	$(CC) $(CCFLAGS) $(ZMQ_INC) -c phish-zmq.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIBZ) phish-zmq.o hash.o

# Clean up

clean:
	@rm -f *.o
	@rm -f lib*.a
