# Makefile for PHISH library: linux box with g++, MPICH

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler settings
# specify your compiler, its flags, and MPI,ZMQ dependencies

CC =		g++
CCFLAGS =	-g -O
ARCHIVE =	ar
ARFLAGS =	-rc

# MPI compiler settings
# only needed to build MPI version of PHISH library
# INC = path for mpi.h, other compiler settings

MPI_INC =	-DMPICH_IGNORE_CXX_SEEK

# ZMQ compile settings
# only needed to build ZMQ or MPI+ZMQ version of PHISH library
# INC = path for zmq.h, other compiler settings

ZMQ_INC =	-I~/zmq

# ---------------------------------------------------------------------
# targets = 3 versions of PHISH library: MPI, MPI+ZMQ, ZMQ
# no need to edit this section

LIB =	libphish.a

mpi:	
	$(CC) $(CCFLAGS) $(MPI_INC) -c phish-mpi.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIB) phish-mpi.o hash.o

mpizmq:	
	$(CC) $(CCFLAGS) $(MPI_INC) $(ZMQ_INC) -DPHISH_MPI_ZMQ -c phish-mpi.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIB) phish-mpi.o hash.o

zmq:
	$(CC) $(CCFLAGS) $(ZMQ_INC) -c phish-zmq.cpp
	$(CC) $(CCFLAGS) -c hash.cpp
	$(ARCHIVE) $(ARFLAGS) $(LIB) phish-zmq.o hash.o

# Clean up

clean:
	@rm -f *.o
	@rm -f libphish.a
